version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expense_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: